[package]
name = "datajoint-core-ffi-c"
version = "0.1.0"
edition = "2018"

[dependencies]
datajoint-core = { path = "../datajoint-core" }
libc = "0.2.101"

[lib]
name="core_ffi"
crate-type = ["cdylib"]